---
name: System::Disk
version: 0.01
author: [Matthew Callaway <mcallawa@genome.wustl.edu>]
abstract: Modules for disk management
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
build_requires:
  Module::Build: 0
  Test::More: 0
  Test::Exception: 0
  Date::Manip::Date: 0
  Date::Manip: 0
  JSON: 0
requires:
  UR: 0
configure_requires:
  Module::Build: 0.340201
provides:
  System::DataSource::Disk:
    file: lib/System/DataSource/Disk.pm
  System::Disk:
    file: lib/System/Disk.pm
  System::Disk::Array:
    file: lib/System/Disk/Array.pm
  System::Disk::Array::Command:
    file: lib/System/Disk/Array/Command.pm
  System::Disk::Array::View::Default::Html:
    file: lib/System/Disk/Array/View/Default/Html.pm
  System::Disk::Assignment:
    file: lib/System/Disk/Assignment.pm
  System::Disk::Assignment::Command:
    file: lib/System/Disk/Assignment/Command.pm
  System::Disk::Command:
    file: lib/System/Disk/Command.pm
  System::Disk::Export:
    file: lib/System/Disk/Export.pm
  System::Disk::Export::Command:
    file: lib/System/Disk/Export/Command.pm
  System::Disk::Filer:
    file: lib/System/Disk/Filer.pm
  System::Disk::Filer::Command:
    file: lib/System/Disk/Filer/Command.pm
  System::Disk::Filer::Command::Usage:
    file: lib/System/Disk/Filer/Command/Usage.pm
  System::Disk::Filer::View::Status::Cgi:
    file: lib/System/Disk/Filer/View/Status/Cgi.pm
  System::Disk::Filer::View::Summary::Cgi:
    file: lib/System/Disk/Filer/View/Summary/Cgi.pm
  System::Disk::Group:
    file: lib/System/Disk/Group.pm
  System::Disk::Group::Command:
    file: lib/System/Disk/Group/Command.pm
  System::Disk::Host:
    file: lib/System/Disk/Host.pm
  System::Disk::Host::Command:
    file: lib/System/Disk/Host/Command.pm
  System::Disk::Mount:
    file: lib/System/Disk/Mount.pm
  System::Disk::Mount::Command:
    file: lib/System/Disk/Mount/Command.pm
  System::Disk::User:
    file: lib/System/Disk/User.pm
  System::Disk::User::Command:
    file: lib/System/Disk/User/Command.pm
  System::Disk::View::Lib:
    file: lib/System/Disk/View/Lib.pm
  System::Disk::View::Status::Html:
    file: lib/System/Disk/View/Status/Html.pm
  System::Disk::Volume:
    file: lib/System/Disk/Volume.pm
  System::Disk::Volume::Command:
    file: lib/System/Disk/Volume/Command.pm
  System::Disk::Volume::Command::Add:
    file: lib/System/Disk/Volume/Command/Add.pm
  System::Disk::Volume::View::Status::Cgi:
    file: lib/System/Disk/Volume/View/Status/Cgi.pm
  System::Disk::Volume::View::Summary::Cgi:
    file: lib/System/Disk/Volume/View/Summary/Cgi.pm
  System::Utility::RRD:
    file: lib/System/Utility/RRD.pm
  System::Utility::SNMP:
    file: lib/System/Utility/SNMP.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
