#! /bin/sh
set -e

die () {
    echo $@
    exit 1
}

# The www-data user is used for the webapp service.
id -u www-data 2>&1 >/dev/null || \
    die "required user www-data doesn't exist"

id -G www-data 2>/dev/null |  \
    grep -q local-systems  || \
    usermod -G local-systems www-data || \
    die "failed to add local-systems group to www-data"

[ -d ~www-data ] && mkdir -p ~www-data
