
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use SDM;

use Test::More;
use Test::Output;
use Test::Exception;

unless ($ENV{SDM_GENOME_INSTITUTE_NETWORKS}) {
    plan skip_all => "Don't assume we can reach SNMP on named hosts for non GI networks";
}

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/../sdm-disk/t/sdm-disk-lib.pm";
ok( SDM::Test::Lib->has_gpfs_snmp == 1, "gpfs ok");
ok( SDM::Test::Lib->testinit == 0, "init db");
ok( SDM::Test::Lib->testdata == 0, "data db");

my $res;
my @res;

@res = SDM::Disk::GpfsDiskPerf->get( filername => 'fakefiler' );
ok( ! @res, "fake filer returns undef" );

@res = SDM::Disk::GpfsDiskPerf->get( filername => 'gpfs-dev' );
$res = shift @res;

ok( ref $res eq "SDM::Disk::GpfsDiskPerf", "object made correctly");
ok( ref $res->filer eq 'SDM::Disk::Filer', "filer object related");
#print Data::Dumper::Dumper $res;

ok( defined $res->filername, "attr set" );
ok( defined $res->gpfsDiskPerfName, "attr set" );
ok( defined $res->gpfsDiskPerfFSName, "attr set" );
ok( defined $res->gpfsDiskPerfStgPoolName, "attr set" );
ok( defined $res->gpfsDiskReadTimeL, "attr set" );
ok( defined $res->gpfsDiskReadTimeH, "attr set" );
ok( defined $res->gpfsDiskWriteTimeL, "attr set" );
ok( defined $res->gpfsDiskWriteTimeH, "attr set" );
ok( defined $res->gpfsDiskLongestReadTimeL, "attr set" );
ok( defined $res->gpfsDiskLongestReadTimeH, "attr set" );
ok( defined $res->gpfsDiskLongestWriteTimeL, "attr set" );
ok( defined $res->gpfsDiskLongestWriteTimeH, "attr set" );
ok( defined $res->gpfsDiskShortestReadTimeL, "attr set" );
ok( defined $res->gpfsDiskShortestReadTimeH, "attr set" );
ok( defined $res->gpfsDiskShortestWriteTimeL, "attr set" );
ok( defined $res->gpfsDiskShortestWriteTimeH, "attr set" );
ok( defined $res->gpfsDiskReadBytesL, "attr set" );
ok( defined $res->gpfsDiskReadBytesH, "attr set" );
ok( defined $res->gpfsDiskWriteBytesL, "attr set" );
ok( defined $res->gpfsDiskWriteBytesH, "attr set" );
ok( defined $res->gpfsDiskReadOps, "attr set" );
ok( defined $res->gpfsDiskWriteOps, "attr set" );
ok( defined $res->filer, "filer attr set" );
#ok( defined $res->volume, "attr set" );

done_testing();
