
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use Sdm;

use Test::More;
use Test::Output;
use Test::Exception;

unless ($ENV{SDM_GENOME_INSTITUTE_NETWORKS}) {
    plan skip_all => "Don't assume we can reach SNMP on named hosts for non GI networks";
}

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
if ($top =~ /deploy/) {
    require "$top/t/sdm-disk-lib.pm";
} else {
    require "$top/../sdm-disk/t/sdm-disk-lib.pm";
}
ok( Sdm::Disk::Lib->has_gpfs_snmp == 1, "has gpfs");
ok( Sdm::Disk::Lib->testinit == 0, "init db");
ok( Sdm::Disk::Lib->testdata == 0, "data db");

my $res;

$res = Sdm::Gpfs::GpfsDiskStatus->get( filername => 'fakefiler' );
ok( ! defined $res, "fake filer returns undef" );

my @res = Sdm::Gpfs::GpfsDiskStatus->get( filername => 'gpfs-dev' );
$res = shift @res;

ok( ref $res eq "Sdm::Gpfs::GpfsDiskStatus", "object made correctly");
ok( $res->filername eq 'gpfs-dev', "filername set");
ok( ref $res->filer eq 'Sdm::Disk::Filer', "filer object related");
#ok( defined $res->volume, "volume attr set");
ok( defined $res->gpfsDiskName, "attr set" );
ok( defined $res->gpfsDiskFSName, "attr set" );
ok( defined $res->gpfsDiskStgPoolName, "attr set" );
ok( defined $res->gpfsDiskStatus, "attr set" );
ok( defined $res->gpfsDiskAvailability, "attr set" );
ok( defined $res->gpfsDiskTotalSpaceL, "attr set" );
ok( defined $res->gpfsDiskTotalSpaceH, "attr set" );
ok( defined $res->gpfsDiskFullBlockFreeSpaceL, "attr set" );
ok( defined $res->gpfsDiskFullBlockFreeSpaceH, "attr set" );
ok( defined $res->gpfsDiskSubBlockFreeSpaceL, "attr set" );
ok( defined $res->gpfsDiskSubBlockFreeSpaceH, "attr set" );

done_testing();
