#!/gsc/bin/perl

use strict;
use warnings;
use Data::Dumper;

BEGIN {
$ENV{UR_DBI_NO_COMMIT} = 1; #Important! A UR commit hook is tested below
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use above "System";
use Test::More tests => 11;


is(System::Search->environment(), 'prod', 'using prod instance of solr');

my @searchable_classes = System::Search->searchable_classes();
cmp_ok(scalar(@searchable_classes), '>', 1, 'found some searchable classes:');
print Dumper \@searchable_classes;

### Tests adding/removing documents

my $individual = System::Individual->create(
    id => -54321,
    common_name => 'search_1',
    name => 'search_test_1',
    upn => 'genome.search_test_1',
    gender => 'Female',
    taxon_id => 1653198737,
);

#Test commit hook
ok(UR::Context->commit, 'commit did not crash');

#Manually get Solr document (duplicates what should have happened in commit hook test)
my @individual_doc = System::Search->generate_document($individual);
is(scalar @individual_doc, 1, 'got a document for test individual');
isa_ok($individual_doc[0], 'WebService::Solr::Document');

ok($individual->delete, 'delete did not crash');
ok(UR::Context->rollback, 'rollback did not crash');


### Tests for search class resolver

#Search class belongs to parent
my $model = System::Model->get(2771359026);
my $model_doc = System::Search->generate_document($model); #Model ID mentioned in ReferenceAlignment.t
ok($model_doc, 'able to produce document for a model subtype');


#Class not being indexed
my $iub_class = System::Search->is_indexable('System::Info::IUB');
ok(!$iub_class, 'returned no search class for IUB info module');

#Class not being indexed though a class up the directory structure is
my $build_class = System::Search->is_indexable(System::Model::Somatic::Report::Variant->create( build_id => 97848505)); #Build ID mentioned in ReferenceAlignment.t
ok(! $build_class, 'returned no search class for a somatic model variant report');

#Not a blessed reference
my $hash_class = System::Search->is_indexable({ hashkey => 'hashvalue'});
ok(!$hash_class, 'returned no search class for an unblessed hash');

