
package SDM::Lims::GridJobsFinished;

class SDM::Lims::GridJobsFinished {
    table_name  => 'GSC.GRID_JOBS_FINISHED',
    data_source => 'SDM::DataSource::GMSchema',
    doc         => 'work with grid jobs',
    id_by => [
        bjob_id     => { is => 'Number' }
    ],
    has => [
        begintime          => { is => 'Date' },
        bjob_user          => { is => 'Text' },
        clusterid          => { is => 'Number' },
        command            => { is => 'Text' },
        completion_time    => { is => 'Number' },
        cpu_used           => { is => 'Number' },
        cwd                => { is => 'Text' },
        dependcond         => { is => 'Text' },
        effic_logged       => { is => 'Number' },
        efficiency         => { is => 'Number' },
        end_time           => { is => 'Date' },
        errfile            => { is => 'Text' },
        exec_host          => { is => 'Text' },
        execcwd            => { is => 'Text' },
        exechome           => { is => 'Text' },
        execuid            => { is => 'Number' },
        execusername       => { is => 'Text' },
        exitstatus         => { is => 'Number' },
        flapping_logged    => { is => 'Number' },
        from_host          => { is => 'Text' },
        hostspec           => { is => 'Text' },
        indexid            => { is => 'Number' },
        infile             => { is => 'Text' },
        job_end_logged     => { is => 'Number' },
        job_scan_logged    => { is => 'Number' },
        job_start_logged   => { is => 'Number' },
        jobgroup           => { is => 'Text' },
        jobid              => { is => 'Number' },
        jobname            => { is => 'Text' },
        jobpid             => { is => 'Number' },
        jobpriority        => { is => 'Number' },
        last_updated       => { is => 'Date' },
        licenseproject     => { is => 'Text' },
        loginshell         => { is => 'Text' },
        mailuser           => { is => 'Text' },
        max_memory         => { is => 'Number' },
        max_swap           => { is => 'Number' },
        maxnumprocessors   => { is => 'Number' },
        mem_requested      => { is => 'Number' },
        mem_requested_oper => { is => 'Text' },
        mem_reserved       => { is => 'Number' },
        mem_used           => { is => 'Number' },
        newcommand         => { is => 'Text' },
        nice               => { is => 'Text' },
        num_cpus           => { is => 'Number' },
        num_nodes          => { is => 'Number' },
        numpgids           => { is => 'Number' },
        numpids            => { is => 'Number' },
        numthreads         => { is => 'Number' },
        options            => { is => 'Number' },
        options2           => { is => 'Number' },
        options3           => { is => 'Number' },
        outfile            => { is => 'Text' },
        parentgroup        => { is => 'Text' },
        pend_time          => { is => 'Number' },
        pendreasons        => { is => 'Text' },
        pid_alarm_logged   => { is => 'Number' },
        postexeccmd        => { is => 'Text' },
        predictedstarttime => { is => 'Date' },
        preexeccmd         => { is => 'Text' },
        prev_stat          => { is => 'Text' },
        projectname        => { is => 'Text' },
        psusp_time         => { is => 'Number' },
        queue              => { is => 'Text' },
        res_requirements   => { is => 'Text' },
        reservetime        => { is => 'Date' },
        rlimit_max_core    => { is => 'Number' },
        rlimit_max_cpu     => { is => 'Number' },
        rlimit_max_data    => { is => 'Number' },
        rlimit_max_fsize   => { is => 'Number' },
        rlimit_max_rss     => { is => 'Number' },
        rlimit_max_stack   => { is => 'Number' },
        rlimit_max_swap    => { is => 'Number' },
        rlimit_max_wallt   => { is => 'Number' },
        run_time           => { is => 'Number' },
        sla                => { is => 'Text' },
        ssusp_time         => { is => 'Number' },
        start_time         => { is => 'Date' },
        stat               => { is => 'Text' },
        stat_changes       => { is => 'Number' },
        stime              => { is => 'Number' },
        submit_time        => { is => 'Date' },
        swap_used          => { is => 'Number' },
        termtime           => { is => 'Date' },
        unkwn_time         => { is => 'Number' },
        usergroup          => { is => 'Text' },
        userpriority       => { is => 'Number' },
        ususp_time         => { is => 'Number' },
        utime              => { is => 'Number' },
    ],
    has_many_optional => [
        psejob => {
            is => 'SDM::Lims::PseJob',
            reverse_as => 'job'
        },
        pse => {
            is => 'SDM::Lims::ProcessStepExecutions',
            via => 'psejob'
        }
    ]
};

1;
