#! /bin/sh
set -e

die () {
    echo $@
    exit 1
}

# We use the local-systems group to make our Sqlite databases
# writable by a non-root user, a member of the local-systems group.
grep -q local-systems /etc/group || \
    groupadd local-systems       || \
    die "failed to add local-systems group"

