
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} = "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use Sdm;

use Test::More;
use Test::Output;
use Test::Exception;

my $s = Sdm::Value::KBytes->get(123123123);
my $v = $s->create_view( perspective => "default", toolkit => "text" );
my $c = $v->content;
ok( $c eq "123,123,123 (123 GB)", "default text view ok");

$s = Sdm::Value::KBytes->get(0);
$v = $s->create_view( perspective => "default", toolkit => "text" );
$c = $v->content;
ok( $c eq "0 (0 KB)", "default text view ok");

done_testing();
