
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use SDM;

use Test::More;
use Test::Exception;

my $a;
my $h;
my $f;
my $e;
my $v;
my $m;

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/sdm-disk-lib.pm";
ok( SDM::Test::Lib->testinit == 0, "ok: init db");

ok( $a = SDM::Disk::Array->get_or_create( name => 'nsams2k1' ), "create array ok");
ok( $h = SDM::Disk::Host->get_or_create( hostname => 'linuscs103' ), "create host ok");
ok( defined $a->assign($h->hostname), "assigned array ok");
ok( $f = SDM::Disk::Filer->get_or_create( name => 'gpfs' ), "create filer ok");
ok( defined $h->assign($f->name), "assigned host ok");
ok( $v = SDM::Disk::Volume->_new( mount_path => '/gscmnt/sata821', filername => 'gpfs', physical_path => '/vol/sata821' ), "create volume ok");
ok( UR::Context->commit(), "commit ok");
done_testing();
