
use strict;
use warnings;
use Data::Dumper;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use SDM;

use Test::More;
use Test::Exception;
use Test::Output;

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/sdm-lib.pm";
ok( SDM::Test::Lib->testinit == 0, "ok: init db");
ok( SDM::Test::Lib->testdata == 0, "ok: init db");

my $filername = "gpfs-dev";
my $hostname = "linuscs107";
my $obj = SDM::Disk::Filer::Command::QuerySnmp->create();
my $snmp = SDM::Utility::SNMP::DiskUsage->create( loglevel => "DEBUG", hostname => $hostname );

my $volumedata = $snmp->acquire_volume_data();
my $gpfsnodedata = $snmp->read_snmp_into_table('gpfsNodeStatusTable');
my $gpfsdiskdata = $snmp->read_snmp_into_table('gpfsDiskPerfTable');
my $gpfsfsdata = $snmp->read_snmp_into_table('gpfsFileSDMPerfTable');

my $ref = $obj->update_volumes( $volumedata, $filername );
$ref = $obj->update_gpfs_disk_perf( $gpfsdiskdata );
$ref = $obj->update_gpfs_fs_perf( $gpfsfsdata );
$ref = $obj->update_gpfs_node( $gpfsnodedata );

#print Data::Dumper::Dumper $ref;
UR::Context->commit();

done_testing();
