
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use Test::More;
use Test::Output;
use Test::Exception;

use_ok( 'Sdm' );

# Start with a fresh database
use FindBin;
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/sdm-disk-lib.pm";

my $t = Sdm::Disk::Lib->new();
ok( $t->testinit == 0, "ok: init db");
ok( $t->testdata == 0, "ok: add data");

my $s = Sdm::Disk::Filer->define_set();
my $v = $s->create_view( perspective => 'table', toolkit => 'xml' );
my $xml = $v->_generate_content();
ok( $xml =~ m!<object type="Sdm::Disk::Filer::Set" id="Sdm::Disk::Filer/And//O:O:">!, "output is XML set");

done_testing();
