
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} = "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use Test::More;
use Test::Output;
use Test::Exception;
use Data::Dumper;

use JSON;

use_ok( 'Sdm' );

# Start with a fresh database
use FindBin;
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/sdm-disk-lib.pm";

my $t = Sdm::Disk::Lib->new();
ok( $t->testinit == 0, "ok: init db");
ok( $t->testdata == 0, "ok: add data");

my $s = Sdm::Disk::Volume->define_set();
my $v = $s->create_view( subject_class_name => "Sdm::Object::Set", perspective => 'table', toolkit => 'json' );
my $got = $v->_generate_content();
use JSON;
my $json = JSON->new();
my $result = $json->decode($got);
ok( scalar @{ $result->{aaData} } > 1, "has content");

done_testing();
