
use strict;
use warnings;

BEGIN {
    $ENV{SDM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use SDM;

use Test::More;
use Test::Output;
use Test::Exception;

unless ($ENV{SDM_GENOME_INSTITUTE_NETWORKS}) {
    plan skip_all => "Don't assume we can reach SNMP on named hosts for non GI networks";
}

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/sdm-disk-lib.pm";
ok( SDM::Test::Lib->has_gpfs_snmp == 1, "gpfs ok");
ok( SDM::Test::Lib->testinit == 0, "init db");
ok( SDM::Test::Lib->testdata == 0, "data db");

my $res;

$res = SDM::Disk::GpfsDiskStatus->get( filername => 'fakefiler' );
ok( ! defined $res, "fake filer returns undef" );

my @res = SDM::Disk::GpfsDiskStatus->get( filername => 'gpfs-dev' );
my $res = shift @res;

ok( ref $res eq "SDM::Disk::GpfsDiskStatus", "object made correctly");
ok( $res->filername eq 'gpfs-dev', "filername set");
ok( ref $res->filer eq 'SDM::Disk::Filer', "filer object related");
#ok( defined $res->volume, "attr set");
ok( defined $res->gpfsDiskName, "attr set" );
ok( defined $res->gpfsDiskFSName, "attr set" );
ok( defined $res->gpfsDiskStgPoolName, "attr set" );
ok( defined $res->gpfsDiskStatus, "attr set" );
ok( defined $res->gpfsDiskAvailability, "attr set" );
ok( defined $res->gpfsDiskTotalSpaceL, "attr set" );
ok( defined $res->gpfsDiskTotalSpaceH, "attr set" );
ok( defined $res->gpfsDiskFullBlockFreeSpaceL, "attr set" );
ok( defined $res->gpfsDiskFullBlockFreeSpaceH, "attr set" );
ok( defined $res->gpfsDiskSubBlockFreeSpaceL, "attr set" );
ok( defined $res->gpfsDiskSubBlockFreeSpaceH, "attr set" );
ok( defined $res->mount_path, "attr set");

done_testing();
