
use strict;
use warnings;

BEGIN {
    $ENV{SYSTEM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use System;

use Test::More;
use Test::Output;
use Test::Exception;

unless ($ENV{SYSTEM_GENOME_INSTITUTE_NETWORKS}) {
    plan skip_all => "Test only valid on GI networks";
}

ok( $ENV{SYSTEM_GENOME_INSTITUTE_NETWORKS} == 1, "ok: GI networks" );
ok( $ENV{SYSTEM_DISK_GPFS_PRESENT} == 1, "ok: GPFS present" );
ok( $ENV{SYSTEM_DEPLOYMENT} eq 'testing', "ok: deployment is testing" );
ok( $ENV{SYSTEM_DATABASE_HOSTNAME} eq 'localhost', "ok: hostname is localhost" );
ok( $ENV{SYSTEM_DATABASE_DRIVER} eq 'SQLite', "ok: driver is sqlite" );
done_testing();
