
use strict;
use warnings;

BEGIN {
    $ENV{SYSTEM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use System;

use Test::More;
use Test::Exception;

my $f;
my $e;
my $v;
my $m;

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/system-lib.pm";
ok( System::Test::Lib->testinit == 0, "ok: init db");

ok( $f = System::Disk::Filer->get_or_create( name => 'nfs11' ), "create filer ok");
ok( $e = System::Disk::Export->get_or_create( filername => 'nfs11', physical_path => '/vol/sata821' ), "create export ok");
ok( $v = System::Disk::Volume->_new( mount_path => '/gscmnt/sata821' ), "create volume ok");
ok( $m = System::Disk::Mount->get_or_create( export_id => $e->id, volume_id => $v->id ), "create mount ok");
ok( UR::Context->commit(), "commit ok");
done_testing();
