
use strict;
use warnings;

BEGIN {
    $ENV{SYSTEM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use Test::More;
use Test::Output;
use Test::Exception;
use Data::Dumper;

use HTML::TreeBuilder;

use_ok( 'System' );
use_ok( 'System::Disk::Volume::Set::View::Summary::Json' );

# Start with a fresh database
use FindBin;
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/system-lib.pm";

my $t = System::Test::Lib->new();
ok( $t->testinit == 0, "ok: init db");
ok( $t->testdata == 0, "ok: add data");

my @s = System::Disk::Volume->define_set();
my $v = $s[0]->create_view( perspective => 'summary', toolkit => 'json' );
my $json = $v->_jsobj();
print Data::Dumper::Dumper $json;

# This must match the data used in System::Test::Lib->testdata
my $expected = {
  'total_kb' => 100,
  'last_modified' => '0000:00:00:00:00:00',
  'used_kb' => 50,
  'capacity' => '50'
};

ok( is_deeply( $json, $expected, "ok: is_deeply" ), "ok: json match");

done_testing();
