
package System::Utility::SNMP::TestSuite;

# Standard modules for my unit test suites
# use base 'Test::Builder::Module';

use strict;
use warnings;

BEGIN {
    $ENV{SYSTEM_DEPLOYMENT} ||= "testing";
    $ENV{MIBS} .= "GPFS-MIB";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use System;

use Test::More;
use Test::Output;
use Test::Exception;

use System::Utility::SNMP;
use Data::Dumper;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

my $live = 1;
my $count = 0;

my $snmp;
my $host;
my $res;
my $result = {};
my $oid;
my $physical_path;
my $mount_path;
my $group;

$snmp = System::Utility::SNMP->create( loglevel => "DEBUG" );
$host = "linuscs107";

$snmp->get_gpfs_node_info($result,$host);
print "result: " . Data::Dumper::Dumper $result;

$snmp->get_gpfs_fsperf_info($result);
print "result: " . Data::Dumper::Dumper $result;

done_testing();
