
use strict;
use warnings;

use System;

use Test::More;
use Test::Exception;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

my $f;
my $e;
my $v;
my $m;

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/system-lib.pm";
ok( System::Test::Lib->testinit == 0, "ok: init db");

ok( $f = System::Disk::Filer->create( name => 'nfs11'), "create filer ok");
ok( $v = System::Disk::Volume->get_or_create( filername => 'nfs11', mount_path => '/gscmnt/sata821', physical_path => '/vol/sata821' ), "get_or_create volume ok");
ok( UR::Context->commit(), "commit ok");
done_testing();
