
package System::Utility::SNMP;

# Standard modules for my unit test suites
# use base 'Test::Builder::Module';

use strict;
use warnings;

BEGIN {
    $ENV{SYSTEM_DEPLOYMENT} ||= "testing";
    $ENV{UR_DBI_NO_COMMIT} = 0;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 0;
};

use System;
use System::Utility::SNMP;

use Test::More;
use Test::Output;
use Test::Exception;

# Start with a fresh database
use File::Basename qw/dirname/;
my $top = dirname $FindBin::Bin;
require "$top/t/system-lib.pm";
ok( System::Test::Lib->testinit == 0, "ok: init db");

my $host = 'linuscs107';
#my $host = "ntap11";

my $obj = System::Utility::SNMP->create( command => 'bad' );
dies_ok { $obj->exec } "ok: dies ok";

my @params = ( command => 'snmpwalk', loglevel => 'DEBUG', hostname => $host );
push @params, ( allow_mount => 0 );

$obj = System::Utility::SNMP::DiskUsage->create( @params );
ok( defined $obj->exec, "ok: snmpwalk found and host present");

#my $oid = "hrSWInstalledTable";
my $oid = "hrSWInstalledName";
my $ref = $obj->run( $oid );
foreach my $item (@$ref) {
    print $item->{value} . "\n";
    last if ( $item->{value} =~ /^"gpfs.base/);
}
